// GENERATED by scripts/build-birthday-emails.py from the approved draft:
// C:/Users/jpoll/Documents/Obsidian/SecondBrain/email-marketing/outputs/2026-09-17-birthday-masterclass-FIRE-rework.md
// Do not hand-edit; edit the draft and regenerate.
export const BIRTHDAY_EMAILS = {
 "joel": {
  "1": {
   "slot": "Thu 9/17 · 1:30 PM CT",
   "subject": "okay, for my birthday I am finally doing this",
   "preheader": "One live class. One time. Tomorrow at 11 AM Central.",
   "body": "{{first_name}},\n\nTomorrow is my birthday.\n\nAnd I'm the one giving the gift.\n\nMy dad taught me something about cars. A sudden noise is usually a cheap fix. But a tick that gets louder for months? That one costs you.\n\nHigh blood pressure is that tick. So is creeping blood sugar. So are hormone changes nobody explains.\n\nMost of us get a pill for each noise. Nobody opens the hood.\n\nSo tomorrow, for my birthday, my wife Annie and I are teaching one free live class:\n\n**The #1 Thing Your Doctor Never Checks**\n\nFriday, September 18. 11 AM Central / 12 PM Eastern. For men and women.\n\nThis is the #1 unlock you need. It's the only time we are doing this masterclass.\n\n[BUTTON: SAVE MY FREE SEAT → bpquiz.com/birthday]\n\nJoel Polley, RN\n\nP.S. Always work alongside your doctor. This class helps you find better questions to bring them."
  },
  "2": {
   "slot": "Thu 9/17 · 6:30 PM CT",
   "subject": "I begged my wife to teach this with me",
   "preheader": "Tomorrow at 11 AM Central. Here's why she said yes.",
   "body": "{{first_name}},\n\nQuick note: if my email earlier today called this \"the #1 hidden reason,\" same class. Clearer name. And now Annie is teaching it with me.\n\nI begged my wife to do this with me.\n\nHere's why.\n\nFor years, people asked me about their blood pressure. Then their blood sugar. Then they'd lower their voice and ask about their hormones.\n\nThree problems. Three pills. Three specialists.\n\nBut in the ER, I learned something. When a smoke alarm goes off, you don't pull the batteries and go back to bed. You look for the fire.\n\nYour numbers are the alarm. The \"pill for every number\" approach quiets the alarm. It doesn't look for the fire.\n\nIt's not your fault nobody showed you where to look.\n\nAnnie knows the hormone side better than anyone I know. Together we show you the #1 thing underneath chronic illness.\n\nTomorrow. 11 AM Central / 12 PM Eastern. Men and women.\n\n[BUTTON: SAVE MY SEAT FOR TOMORROW → bpquiz.com/birthday]\n\nJoel\n\nP.S. Keep working alongside your doctor. Come find the fire with us."
  },
  "3": {
   "slot": "Fri 9/18 · 7:00 AM CT",
   "subject": "it's my birthday, and I have a gift for you",
   "preheader": "Live at 11 AM Central. One time only.",
   "body": "{{first_name}},\n\nToday I turn another year older.\n\nHere's the gift I want to give you.\n\nYears ago, I worked nights. Lots of caffeine to stay awake. Eating all through the night. My blood pressure climbed, early. My father and grandfather both died young.\n\nI could have blamed my genes and waited my turn.\n\nBut I went looking underneath.\n\nAnd a few right changes later, my blood pressure came down while I was still working nights.\n\nWhat I found is the #1 thing underneath chronic illness. That's my birthday gift to you, and I'm revealing it live at 11.\n\nPlus, a surprise giveaway for everyone on the live call.\n\n**The #1 Thing Your Doctor Never Checks**\nToday. 11 AM Central / 12 PM Eastern. Annie and I, live.\n\nThis is the only time we are doing this masterclass.\n\n[BUTTON: SAVE MY SEAT FOR 11 AM → bpquiz.com/birthday]\n\nJoel Polley, RN\n\nP.S. Want to make my birthday? Hit reply with \"I'll be there.\"\n\n<small>Giveaway: no purchase necessary. Must be on the live call to win.</small>"
  },
  "4": {
   "slot": "Fri 9/18 · 10:50 AM CT",
   "subject": "{{first_name}}, the room is open (10 minutes)",
   "preheader": "Come in now and get settled.",
   "body": "{{first_name}},\n\nThe room is open.\n\nWe start in 10 minutes. 11 AM Central / 12 PM Eastern.\n\nGrab a glass of water and your last blood pressure reading.\n\nStay to the end. The surprise giveaway happens live.\n\n[BUTTON: JOIN THE CLASS NOW → {{ZOOM_JOIN_URL}}]\n\nJoel\n\n<small>No purchase necessary. Must be on the live call to win.</small>"
  },
  "5": {
   "slot": "Fri 9/18 · 1:30 PM CT",
   "subject": "You didn't miss it. | thank you for the best birthday",
   "preheader": "Plus where we go from here, Monday night.",
   "body": "{{first_name}},\n\nThank you for spending my birthday with us.\n\nTeaching the #1 thing underneath chronic illness was the best gift I got all day.\n\n**[IF REPLAY]**\nIf you couldn't make it live, you didn't miss everything. Here's the recording: [REPLAY LINK]\n\n**[IF NO REPLAY]**\nIf you couldn't make it, I'm sorry you missed it. There is no recording. But Monday night, we pick up right where we left off.\n\nHere's the next step.\n\nMonday, Annie and I teach our weekly class:\n\n**The 4 Biggest Mistakes Making Your Fatigue, Blood Pressure, Weight, A1C & Hormone Symptoms Worse After 40**\n\nMonday, September 21. 6 PM Central / 7 PM Eastern. Free.\n\n[BUTTON: SAVE MY MONDAY SEAT → bpquiz.com/masterclass]\n\nOur family rests for the Sabbath from sundown tonight to sundown Saturday. You'll hear from me again Sunday.\n\nJoel\n\nP.S. Hit reply with the one thing that clicked for you today. I read every one."
  },
  "6": {
   "slot": "Sun 9/20 · 9:00 AM CT",
   "subject": "nobody looked at his back",
   "preheader": "The question that should come before the next prescription.",
   "body": "{{first_name}},\n\nThere's a story I tell about a man with terrible back pain.\n\nHe got pain pills. The pain came back. Stronger pills. Then stronger.\n\nNobody asked why his back hurt.\n\nHe had a knife in his back.\n\nPull the knife out, and the body can do what God designed it to do.\n\nI tell that story because I lived the other side of it. As a nurse, I handed out thousands of pills. For years, I never asked why.\n\nOn my birthday, we showed you the #1 thing underneath chronic illness. That's the knife most people never see.\n\nMonday night, we show you the 4 biggest mistakes that keep pushing it deeper.\n\nMonday, September 21. 6 PM Central / 7 PM Eastern. Free. For men and women.\n\n[BUTTON: SAVE MY SEAT FOR MONDAY → bpquiz.com/masterclass]\n\nJoel Polley, RN\n\nP.S. Always work alongside your doctor on your medications. Finding the cause gives you both better choices."
  },
  "7": {
   "slot": "Mon 9/21 · 8:30 AM CT",
   "subject": "tonight: your questions, answered before you ask",
   "preheader": "Live at 6 PM Central. Here's what people ask me.",
   "body": "{{first_name}},\n\nTonight at 6 PM Central / 7 PM Eastern, Annie and I go live. Here are the questions I hear most, and the false belief hiding inside each one.\n\n**\"I'm on medication. Is this still for me?\"**\nThe false belief: medication and finding the cause don't mix. They do. We teach you to work alongside your doctor, never around them.\n\n**\"I've tried everything.\"**\nThe false belief: more effort fixes it. You may have tried many things aimed at the alarm. Tonight is about what sets the alarm off.\n\n**\"It runs in my family.\"**\nThe false belief: genes decide everything. Genetics writes the recipe. Lifestyle bakes the cake.\n\n**\"This is a women's hormone thing, right?\"**\nThe false belief: men don't have hormones. Men, this one is for you too.\n\n**\"I missed Friday. Will I be lost?\"**\nNo. On Friday we showed the #1 thing underneath chronic illness. Tonight stands on its own.\n\n**\"Do I have to buy anything?\"**\nNo. The class is free. At the end, we tell you about the Change My Life Challenge for anyone who wants to go further.\n\n**The 4 Biggest Mistakes Making Your Fatigue, Blood Pressure, Weight, A1C & Hormone Symptoms Worse After 40**\nTonight. 6 PM Central / 7 PM Eastern.\n\n[BUTTON: SAVE MY SEAT FOR TONIGHT → bpquiz.com/masterclass]\n\nJoel\n\nP.S. Come a few minutes early. We start on time."
  },
  "8": {
   "slot": "Mon 9/21 · 5:55 PM CT",
   "subject": "WE'RE LIVE",
   "preheader": "Annie and I are opening the room now.",
   "body": "{{first_name}},\n\nAnnie and I are opening the room right now.\n\n6 PM Central / 7 PM Eastern.\n\nThe 4 biggest mistakes making your blood pressure, blood sugar, weight, and hormone symptoms worse.\n\nCome as you are.\n\n[BUTTON: JOIN US LIVE → bpquiz.com/masterclass]\n\nJoel"
  },
  "9": {
   "slot": "Mon 9/21 · 8:45 PM CT",
   "subject": "the challenge starts tomorrow night",
   "preheader": "3 live nights. $97. Here's what happens.",
   "body": "{{first_name}},\n\nOn my birthday, we showed you the #1 thing underneath chronic illness.\n\nTonight, we showed you the 4 mistakes that keep people stuck.\n\nNow comes the part where you do something with it.\n\n**The Change My Life Challenge**\nSeptember 22, 23, and 24\n6 PM Central / 7 PM Eastern, live on Zoom\n$97\n48-hour replays if life happens\n\nNight 1: Lower Your Numbers Naturally.\nNight 2: Bring Sexy Back.\nNight 3: Take Back Your Future.\n\nThree nights with two nurses. Finding what to work on first, and building your plan around it, alongside your doctor.\n\nIt starts tomorrow night.\n\n[BUTTON: I'M IN FOR TOMORROW → changemylifechallenge.com]\n\nJoel Polley, RN\n\nP.S. Missed tonight? The challenge still works for you. Night 1 starts at the beginning."
  },
  "10": {
   "slot": "Tue 9/22 · 8:00 AM CT",
   "subject": "we start tonight at 6 PM Central",
   "preheader": "Last call. Here's the only question.",
   "body": "{{first_name}},\n\nTonight the Change My Life Challenge begins.\n\n6 PM Central / 7 PM Eastern. Three live nights. $97. 48-hour replays.\n\nHere's what 20 years in the ER taught me.\n\nNobody in the trauma bay is rich. And nobody in the trauma bay is busy.\n\nOn a gurney, your calendar doesn't matter. Your health is the real money.\n\nSo I'll ask you what I ask at the end of every class: what does it cost you to wait another year?\n\nIf $97 would take food off your table, don't join. I mean that.\n\nIf it wouldn't, come start with us tonight.\n\n[BUTTON: SAVE MY SEAT FOR TONIGHT → changemylifechallenge.com]\n\nSee you tonight,\nJoel\n\nP.S. This is for men and women both. Forward this to the person you want sitting next to you tonight.\n\n---"
  }
 },
 "annie": {
  "1": {
   "slot": "Thu 9/17 · 1:30 PM CT",
   "subject": "Girl, my husband is giving YOU his birthday gift",
   "preheader": "Meet Joel. One live class tomorrow, 11 AM Central.",
   "body": "{{first_name}},\n\nCan I brag on my husband for a minute?\n\nHis name is Joel Polley.\n\nHe's a registered nurse, like me.\n\n20 years in the ER and ICU.\n\nGirl, he has seen it all.\n\nHe's the blood pressure and blood sugar side of our house.\n\nI'm the hormone side.\n\nTomorrow is his birthday.\n\nAnd instead of a party, he said, \"I want to give people a gift.\"\n\nSo tomorrow, we're teaching one free live class together:\n\n**The #1 Thing Your Doctor Never Checks**\n\nFriday. 11 AM Central / 12 PM Eastern.\n\nHe calls it the #1 unlock. It's the only time we're doing this masterclass.\n\nAnd this one is for the men in your life too.\n\nBring your husband. Your dad. Your brother. Your friend.\n\n[BUTTON: SAVE YOUR SEAT → bpquiz.com/birthday]\n\nCheering for you girl,\nEveryday Nurse Annie\n\nP.S. Don't forget to Love The Girl You're In."
  },
  "2": {
   "slot": "Thu 9/17 · 6:30 PM CT",
   "subject": "\"I look like a cow\" (what my girls heard)",
   "preheader": "Your hormones are not a separate problem. Tomorrow, 11 AM Central.",
   "body": "{{first_name}},\n\nNow, I have to tell you something.\n\nYears ago, my little girls caught me in the mirror.\n\nPinching my belly.\n\n\"I look like a cow.\"\n\nOne of them looked at me. \"Me? How?\"\n\nGirl, I stopped right there.\n\nMy daughters learn what to think about themselves from me.\n\nHere's what I know now.\n\nThe belly. The mood. The blood pressure. The sugar cravings.\n\nThey are not a bunch of separate problems.\n\nThey're alarms. And most of us get handed a pill for every alarm.\n\nIt's not your fault nobody looked underneath.\n\nTomorrow, Joel and I show you the #1 thing underneath chronic illness.\n\nFriday. 11 AM Central / 12 PM Eastern.\n\nBring your husband too. His hormones and blood pressure are talking the same way.\n\n[BUTTON: SAVE YOUR SEAT → bpquiz.com/birthday]\n\nEveryday Nurse Annie\n\nP.S. Keep working alongside your doctor, girl. Come find the cause with us."
  },
  "3": {
   "slot": "Fri 9/18 · 7:00 AM CT",
   "subject": "It's Joel's birthday (and you get the gift) 🎁",
   "preheader": "Live at 11 AM Central. One time only.",
   "body": "{{first_name}},\n\nToday is my husband's birthday.\n\nI married a man who asks \"why.\"\n\nWhy is the number up?\n\nWhy is she so tired?\n\nWhy does nobody look underneath?\n\nWhen his own blood pressure climbed on night shift, he didn't just accept it.\n\nHe went looking.\n\nSo today, his gift to you is what he found: the #1 thing underneath chronic illness.\n\nI'll be right there with him for the hormone side.\n\nAnd girl, there's a surprise giveaway on the live call.\n\n**The #1 Thing Your Doctor Never Checks**\nToday. 11 AM Central / 12 PM Eastern.\n\nThis is the only time we're doing this masterclass.\n\nThis one is for the men in your life too. Send it to him.\n\n[BUTTON: SAVE MY SEAT FOR 11 AM → bpquiz.com/birthday]\n\nEveryday Nurse Annie\n\nP.S. Reply \"Happy birthday Joel\" and I'll make sure he sees every one.\n\n<small>Giveaway: no purchase necessary. Must be on the live call to win.</small>"
  },
  "4": {
   "slot": "Fri 9/18 · 10:50 AM CT",
   "subject": "Girl, the room is open (10 minutes)",
   "preheader": "Come in now. Bring him too.",
   "body": "{{first_name}},\n\nThe room is open.\n\nWe start in 10 minutes.\n\n11 AM Central / 12 PM Eastern.\n\nGrab your water. Grab your husband.\n\nStay to the end for the surprise giveaway.\n\n[BUTTON: COME IN NOW → {{ZOOM_JOIN_URL}}]\n\nCome on. We're waiting on you.\n\nEveryday Nurse Annie\n\n<small>No purchase necessary. Must be on the live call to win.</small>"
  },
  "5": {
   "slot": "Fri 9/18 · 1:30 PM CT",
   "subject": "You didn't miss it, girl | Thank you for coming to Joel's party",
   "preheader": "Where we go from here, Monday night.",
   "body": "{{first_name}},\n\nThank you for celebrating Joel with us.\n\nHe's still smiling.\n\n**[IF REPLAY]**\nCouldn't make it live? You didn't miss everything.\n\nHere's the recording: [REPLAY LINK]\n\n**[IF NO REPLAY]**\nCouldn't make it? I'm sorry, girl.\n\nThere's no recording.\n\nBut Monday night, we pick up right where we left off.\n\nEvery Monday, Joel and I teach together:\n\n**The 4 Biggest Mistakes Making Your Fatigue, Blood Pressure, Weight, A1C & Hormone Symptoms Worse After 40**\n\nMonday, September 21.\n\n6 PM Central / 7 PM Eastern.\n\nFree.\n\n[BUTTON: SAVE MY MONDAY SEAT → restoreherhormones.com/masterclass]\n\nOur family rests for the Sabbath from sundown tonight to sundown Saturday.\n\nSee you on the other side.\n\nEveryday Nurse Annie\n\nP.S. Don't forget to Love The Girl You're In."
  },
  "6": {
   "slot": "Sun 9/20 · 9:00 AM CT",
   "subject": "\"Let's pretend she's our mommy\"",
   "preheader": "The day my girls picked another mom.",
   "body": "{{first_name}},\n\nI took my girls to the park.\n\nThey were 4 and 6.\n\nA woman walked by. Full of energy. Glowing.\n\nMy girls watched her.\n\nAnd for days after, they played a game.\n\n\"Let's pretend she's our mommy.\"\n\nGirl, that one stung.\n\nI didn't scold them.\n\nI had to become, once again, the mom they look up to.\n\nOn Joel's birthday, we showed you the #1 thing underneath chronic illness.\n\nTomorrow night, we show you the 4 biggest mistakes that keep women stuck. And men too.\n\nMonday. 6 PM Central / 7 PM Eastern. Free.\n\nYour daughter is watching.\n\n[BUTTON: SAVE MY SEAT FOR MONDAY → restoreherhormones.com/masterclass]\n\nCheering for you girl,\nEveryday Nurse Annie\n\nP.S. Bring your husband. We teach his side too."
  },
  "7": {
   "slot": "Mon 9/21 · 8:30 AM CT",
   "subject": "Tonight: the questions you're scared to ask",
   "preheader": "Live at 6 PM Central. I answered them here first.",
   "body": "{{first_name}},\n\nTonight at 6 PM Central / 7 PM Eastern, Joel and I go live.\n\nHere's what women ask me most.\n\nAnd the lie hiding inside each question.\n\n**\"Isn't this just aging?\"**\nThe lie: tired and moody is your new normal. Your body is sending signals. We teach you to read them.\n\n**\"I'm on medication. Can I still come?\"**\nThe lie: it's pills or nothing. You work alongside your doctor. Always.\n\n**\"I've tried every diet.\"**\nThe lie: you need more willpower. You need to know what's underneath.\n\n**\"Is it only for women?\"**\nThe lie: men don't have hormones. Bring him. His numbers are talking too.\n\n**\"I missed Friday.\"**\nThe lie: you're behind. Tonight stands on its own.\n\n**\"Do I have to buy something?\"**\nNo. It's free. At the end, we share the Change My Life Challenge for anyone who wants more.\n\n**The 4 Biggest Mistakes Making Your Fatigue, Blood Pressure, Weight, A1C & Hormone Symptoms Worse After 40**\nTonight. 6 PM Central / 7 PM Eastern.\n\n[BUTTON: SAVE MY SEAT FOR TONIGHT → restoreherhormones.com/masterclass]\n\nEveryday Nurse Annie\n\nP.S. Come as you are, girl."
  },
  "8": {
   "slot": "Mon 9/21 · 5:55 PM CT",
   "subject": "Girl, WE'RE LIVE",
   "preheader": "Joel and I are opening the room now.",
   "body": "{{first_name}},\n\nWe're opening the room right now.\n\n6 PM Central / 7 PM Eastern.\n\nThe 4 biggest mistakes making your hormones, weight, and numbers worse.\n\nCome as you are.\n\n[BUTTON: COME IN → restoreherhormones.com/masterclass]\n\nEveryday Nurse Annie"
  },
  "9": {
   "slot": "Mon 9/21 · 8:45 PM CT",
   "subject": "Tomorrow night, we start (3 nights)",
   "preheader": "$97. Two nurses. Your plan.",
   "body": "{{first_name}},\n\nOn Joel's birthday, we showed you the #1 thing underneath chronic illness.\n\nTonight, we showed you the 4 mistakes.\n\nNow, girl, it's time to do something with it.\n\n**The Change My Life Challenge**\n\nSeptember 22, 23, and 24.\n\n6 PM Central / 7 PM Eastern. Live on Zoom.\n\n$97.\n\n48-hour replays if life happens.\n\nNight 1: Lower Your Numbers Naturally.\n\nNight 2: Bring Sexy Back.\n\nNight 3: Take Back Your Future.\n\nThree nights. Two nurses. Your first step, alongside your doctor.\n\nIt starts tomorrow night.\n\n[BUTTON: I'M IN → changemylifechallenge.com]\n\nCheering for you girl,\nEveryday Nurse Annie\n\nP.S. Missed tonight? You can still join. Night 1 starts at the beginning."
  },
  "10": {
   "slot": "Tue 9/22 · 8:00 AM CT",
   "subject": "Tonight we begin (last call, girl)",
   "preheader": "6 PM Central. Three live nights.",
   "body": "{{first_name}},\n\nTonight the Change My Life Challenge begins.\n\n6 PM Central / 7 PM Eastern.\n\n$97. Three nights. 48-hour replays.\n\nRemember my girls at the park?\n\nI didn't need a new body overnight.\n\nI needed a first step.\n\nThis is yours.\n\nIf $97 would take food off your table, please don't join. I mean that.\n\nIf it wouldn't, come start with us tonight.\n\n[BUTTON: SAVE MY SEAT → changemylifechallenge.com]\n\nSee you tonight,\nEveryday Nurse Annie\n\nP.S. Don't forget to Love The Girl You're In.\n\n---"
  }
 }
};
